spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employeeDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # keep these here, or move ddl/show-sql to shared application.yml if you prefer
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
